- name: nginx install and run
  hosts: frontend
  become: yes  # to run as root user sudo access
  tasks:
   - name: install nginx server
     ansible.builtin.package:
        name: nginx
        state: present

   - name: start nginx service  
     ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
  

      