- name: variables from inventory
  hosts: local
  connection: local
  tasks:
    - name: print user information
      ansible.builtin.debug:
        msg: "Hello my details is : {{ COURSE }}, Duration  {{ DURATION }} , Trainer: {{ TRAINER }}" # vars reference should be surrounded by double quotes
